dist: trusty 
# используем Ubuntu 14.04 Trusty Tahr (а не 12.02 Precise Pangolin)
sudo: required 
# используем Virtual Machine (а не Docker container)
language: cpp 
# на практике разницы между специфичным для C++ окружением
# и, скажем, python -- никакой. Но пусть будет cpp.
os:
# будем прогонять CI и на Linux, и на Mac OS X...
    - linux
    - osx
compiler:
# ... и с помощью GCC, и Clang
    - gcc
    - clang
env:
# список переменных окружения, влияющих на матрицу сборки:
    - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
    - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release
    - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
    - TARGET_CPU=x86 BUILD_CONFIGURATION=Release
matrix:
    exclude:
    # вручную исключим ненужные элементы из матрицы сборки:
    - os: osx
      compiler: gcc
    - os: osx
      env: TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
    - os: osx
      env: TARGET_CPU=x86 BUILD_CONFIGURATION=Release
install:
    # скрипт настройки среды и установки зависимостей:
    - source ci/travis/install-$TRAVIS_OS_NAME.sh
script:
    # скрипт сборки и тестирования проекта:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU
    - cmake --build .
    - ctest --output-on-failure
deploy:
    # выкладываем tagged-коммиты на GitHub Releases:
    provider: releases
    file:
        # список артефактов
        - file1.pkg
        - file2.pkg
        - ...
    skip_cleanup: true
    overwrite: true
    
    api_key:
        secure: "d+KActeHULBhaWDKg5QqD6O6usFzQxd/3swrc36wOJEEZGCJzNke2TlveuXg84fh5HMYFr0VrS6wWCxe7cgfT7oB2FRhHk0zxOBo0I/HiIV5Eg4qZSlg0xmWjD8JBAz4QB0JAnvLKjaRpTHUQofW8d5ZxRKj4hV/VxUynHgZgBTcLQmpmOBc0xJ5BVdymJ4qr8Jp9xUPS8XQk5bBWChf7yy3F2Drb4pyqou/h2DE+RYda/VeUimSrnMu1b+QnDhAn3bCxeTipMey8CkXYVUBKY1C7CurV9QAt8H+If8BrAOA740UrDhhCiP1D7VPpWTNke4IyBNA/fgBjmPOSunNiThVCnlrKDeGSHxSMIoP0tUr6MoBS0YRCLA1fH2qkpcmYU7G3vOQqEozSAogxZsuME4PfX7T4BW5R2XFKr+bkd/QDsr0S7CeHDQhAVlnfbXIw5u36IDGIqEhG2rHGtBljoU53g8XcpqiUZpL21dOmpfAxbxxRBQHdh2dPcWy/6YVj3EY9bXbHDKaPh8RTScxsRQo+ZkpGTiFHAsCyte50R9SI1D2buG06M0kILAZciDCeZ1LolRMKr6oeUhEOHQsbSXMiHLWG/AJ/gl1AE9Lhp2YwmSSPTeXvvaAzyZHs3A7a98Ye/H6Of7iv/uxUu7JZui9guirhBDq7r3SkLj4jiA="
    on:
        tags: true
